atpradical/flash-cards-team

src/components/ui/slider/slider.tsx, src/components/ui/text-field/textField.tsx
guys, please admire my work on adding forwardRef into textField & slider components
=> feature: forwardRef

src/App.tsx, src/components/ui/radio/index.ts, src/components/ui/radio/radio.stories.tsx, src/components/ui/radio/radio.tsx, src/shared/ui/form-components/controlled-radio/controlled-radio.tsx, src/shared/ui/form-components/controlled-radio/index.ts
Controlled radio at your service
=> Controlled radio

src/App.tsx, src/components/ui/forms/forgot-password-form/forgotPasswordForm.module.scss, src/components/ui/forms/forgot-password-form/forgotPasswordForm.stories.tsx, src/components/ui/forms/forgot-password-form/forgotPasswordForm.tsx, src/components/ui/forms/forgot-password-form/index.ts
If you forgot your password, use this component
=> Form forgot password

src/components/ui/table-filter-bar/index.ts, src/components/ui/table-filter-bar/table-filter-bar.module.scss, src/components/ui/table-filter-bar/table-filter-bar.stories.tsx, src/components/ui/table-filter-bar/table-filter-bar.tsx
Table-filter-bar without logic
Нужны правки в стилях компонент Button и TabsSwitcher, таски с рефактором создал
=> [Component]-Table-filter-bar

src/app/router.tsx, src/components/ui/deck-list-table/deck-list-table.stories.tsx, src/components/ui/deck-list-table/deck-list-table.tsx, src/components/ui/deck-table/deck-table.tsx, src/pages/card-page/card-page.tsx, src/pages/deck-list-page/deck-list-page.tsx, src/pages/deck-page/deck-page.tsx
=> feature: routing for deck-list deck and card pages

src/components/forms/dialog-forms/add-new-card-dialog-form/add-new-card-dialog-form.tsx, src/components/layout/deckSettingsDropdown/dropdownSettings.tsx, src/components/ui/deck-table/deck-table.stories.tsx, src/components/ui/deck-table/deck-table.tsx, src/components/ui/deck-title/deck-title.stories.tsx, src/components/ui/deck-title/deck-title.tsx, src/components/ui/dropdown/dropdown.stories.tsx, src/pages/deck-page/deck-page.tsx, src/shared/ui/flex-container/flex-container.module.scss, src/shared/ui/flex-container/flex-container.tsx
hi all! look at my Routing deck branch to get pleasure
=> Routing deck 2

src/components/ui/layout-components/cards-header/cards-header.tsx, src/components/ui/primitives/pagination/pagination.module.scss, src/components/ui/primitives/radio/radio.mock.ts, src/components/ui/primitives/radio/radio.module.scss, src/components/ui/primitives/radio/radio.stories.tsx, src/components/ui/primitives/radio/radio.tsx, src/components/ui/primitives/select/select.mock.ts, src/components/ui/primitives/select/select.module.scss, src/components/ui/primitives/select/select.stories.tsx, src/components/ui/primitives/select/select.tsx, src/components/ui/primitives/slider/slider.module.scss, src/components/ui/primitives/slider/slider.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.mock.ts, src/components/ui/primitives/tab-switcher/tab-switcher.module.scss, src/components/ui/primitives/tab-switcher/tab-switcher.stories.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.tsx, src/pages/card-page/card-page.tsx, src/pages/check-email-page/check-email-page.tsx, src/pages/deck-list-page/deck-list-page.tsx, src/pages/deck-page/deck-page.tsx, src/pages/error-404-page/error-404-page.tsx, src/pages/password-recovery-page/password-recovery-page.tsx, src/pages/password-reset/password-reset.tsx, src/pages/profile-page/profile-page.tsx, src/pages/sign-in-page/sign-in-page.tsx, src/pages/sign-up-page/sign-up-page.tsx
flexcontainer reused for exist components and pages to provide better user experience.
=> Refactor flexcontainer reuse

src/components/forms/create-new-password-form/create-new-password-form.tsx, src/components/forms/forgot-password-form/forgot-password-form.tsx, src/components/forms/self-rate-form/self-rate-form.module.scss, src/components/forms/sign-in-form/sign-in-form.tsx, src/components/forms/sign-up-form/sign-up-form.tsx, src/components/ui/layout-components/check-email/check-email.tsx, src/components/ui/layout-components/learn-card/learn-card.module.scss, src/components/ui/layout-components/learn-card/learn-card.tsx, src/components/ui/layout-components/personal-info/personal-info.module.scss, src/components/ui/layout-components/personal-info/personal-info.tsx, src/components/ui/layout-components/profile-dropdown/profile-dropdown.module.scss, src/components/ui/layout-components/profile-dropdown/profile-dropdown.tsx, src/components/ui/layout-components/table-filter-bar/table-filter-bar.tsx, src/components/ui/primitives/card/card.stories.tsx, src/components/ui/primitives/checkbox/checkbox.tsx, src/components/ui/primitives/pagination/pagination.module.scss, src/components/ui/primitives/pagination/pagination.tsx, src/components/ui/primitives/radio/radio.tsx, src/components/ui/primitives/select/select.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.tsx, src/components/ui/primitives/table/table.tsx, src/components/ui/primitives/text-field/textField.tsx, src/components/ui/primitives/typography/typography.module.scss, src/components/ui/primitives/typography/typography.tsx
hi guys! look at my branch Refactor-Typography!
=> refactor Typography component

src/components/ui/layout-components/personal-info/personal-info.module.scss, src/components/ui/layout-components/personal-info/personal-info.tsx, src/components/ui/primitives/button/button.module.scss
Button component styles minor refactoring.
=> refactor: minor button styles refactoring

src/components/forms/dialog-forms/add-new-card-dialog-form/add-new-card-dialog-form.stories.tsx, src/components/forms/dialog-forms/add-new-card-dialog-form/add-new-card-dialog-form.tsx, src/components/ui/layout-components/deck-title/deck-title.module.scss, src/pages/deck-page/deck-page.module.scss, src/pages/deck-page/deck-page.tsx, src/services/cards/cards.types.ts, src/services/flashcards-api.ts
usrl for test:
http://localhost:5173/deck/cly7c2vqa0drxpb015rp9sbi7
=> create-card on deck page

src/components/ui/layout-components/actions/actions.styles.ts, src/components/ui/layout-components/actions/actions.tsx, src/components/ui/layout-components/check-email/check-email.styles.ts, src/components/ui/layout-components/check-email/check-email.tsx, src/components/ui/layout-components/deck-list-table/deck-list-table.styles.ts, src/components/ui/layout-components/deck-list-table/deck-list-table.tsx, src/components/ui/layout-components/deck-table/deck-table.styles.ts, src/components/ui/layout-components/deck-table/deck-table.tsx, src/components/ui/layout-components/deck-title/deck-title.styles.ts, src/components/ui/layout-components/deck-title/deck-title.tsx, src/components/ui/layout-components/personal-info/personal-info.styles.ts, src/components/ui/layout-components/personal-info/personal-info.tsx, src/components/ui/layout-components/profile-dropdown/profile-dropdown.module.scss, src/components/ui/layout-components/profile-dropdown/profile-dropdown.styles.ts, src/components/ui/layout-components/profile-dropdown/profile-dropdown.tsx, src/components/ui/layout-components/settings-dropdown/settings-dropdown.module.scss, src/components/ui/layout-components/settings-dropdown/settings-dropdown.styles.ts, src/components/ui/layout-components/settings-dropdown/settings-dropdown.tsx, src/components/ui/layout-components/table-filter-bar/table-filter-bar.styles.ts, src/components/ui/layout-components/table-filter-bar/table-filter-bar.tsx, src/components/ui/layout-components/user-profile/user-profile.styles.ts, src/components/ui/layout-components/user-profile/user-profile.tsx, src/shared/enums/path.ts
=> decomposition layout components

src/components/forms/dialog-forms/add-new-card-dialog-form/add-new-card-dialog-form.stories.tsx, src/components/forms/dialog-forms/add-new-card-dialog-form/add-new-card-dialog-form.tsx, src/components/forms/dialog-forms/add-new-deck-dialog-form/add-new-deck-dialog-form.stories.tsx, src/components/forms/dialog-forms/add-new-deck-dialog-form/add-new-deck-dialog-form.tsx, src/pages/deck-list-page/deck-list-page.tsx, src/pages/deck-page/deck-page.tsx, src/services/decks/deck.types.ts, src/services/flashcards-api.ts
=> feature: create new deck on deck-list page

src/components/forms/dialog-forms/deck-dialog-form/deck-dialog-form.tsx, src/components/ui/layout-components/actions/actions.stories.ts, src/components/ui/layout-components/actions/actions.tsx, src/components/ui/layout-components/deck-list-table/deck-list-table.stories.tsx, src/components/ui/layout-components/deck-list-table/deck-list-table.tsx, src/components/ui/layout-components/deck-table/deck-table.tsx, src/pages/deck-list-page/deck-list-page.tsx
hi) look at my new feature pls
=> feature: redirect & added id for openHandlers

src/components/forms/dialog-forms/card-dialog-form/card-dialog-form.tsx, src/components/forms/dialog-forms/container-components/dialog-form-footer.tsx, src/components/forms/dialog-forms/container-components/dialog-from-header.tsx, src/components/forms/dialog-forms/deck-dialog-form/deck-dialog-form.tsx, src/components/forms/dialog-forms/delete-dialog-form/delete-dialog-form.tsx, src/components/forms/dialog-forms/delete-dialog-form/delete-form.stories.tsx, src/components/ui/design-system/color-pallet/color-pallet.module.scss, src/components/ui/design-system/color-pallet/color-pallet.tsx, src/components/ui/design-system/iconography/iconography.module.scss, src/components/ui/design-system/iconography/iconography.tsx, src/components/ui/layout-components/actions/actions.tsx, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.tsx, src/components/ui/layout-components/tables/deck-table/deck-table.tsx, src/pages/deck-list-page/deck-list-page.tsx, src/pages/deck-page/deck-page.tsx, src/services/flashcards-api.ts, src/shared/enums/dialogs.enum.ts, src/shared/ui/form-components/controlled-text-field/controlled-text-field.tsx, src/shared/ui/page/page.tsx
=> Query delete card

src/components/ui/layout-components/table-filter-bar/table-filter-bar.styles.ts, src/components/ui/layout-components/table-filter-bar/table-filter-bar.tsx, src/components/ui/primitives/slider/slider.tsx
Hi, I'm ready to show my new feature
ps: !! doesn't work some styles !!
=> decomposition with label for slider

src/components/ui/layout-components/table-filter-bar/table-filter-bar.stories.tsx, src/components/ui/layout-components/table-filter-bar/table-filter-bar.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.stories.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.tsx, src/pages/deck-list-page/deck-list-page.tsx, src/services/decks/deck.types.ts, src/services/decks/decks-api.ts, src/services/flashcards-api.ts
написала запрос me для демонстрации, в таске этого не было
=> feature: filter by AuthorId & favoritedBy

src/components/ui/layout-components/table-filter-bar/table-filter-bar.tsx, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.module.scss, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.tsx, src/pages/deck-list-page/deck-list-page.tsx
Fixed placeholders & links for DeckListTable
=> refactor links into DeckListTable

src/components/forms/dialog-forms/card-dialog-form/card-dialog-form.stories.tsx, src/components/forms/dialog-forms/deck-dialog-form/deck-dialog-form.stories.tsx, src/components/forms/personal-Info-form/personal-info-form.stories.tsx, src/components/ui/layout-components/table-filter-bar/table-filter-bar.stories.tsx, src/components/ui/layout-components/table-filter-bar/table-filter-bar.tsx, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.stories.tsx, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.tsx, src/components/ui/layout-components/tables/deck-table/deck-table.stories.tsx, src/components/ui/layout-components/tables/deck-table/deck-table.tsx, src/components/ui/primitives/pagination/pagination.stories.tsx, src/components/ui/primitives/pagination/pagination.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.stories.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.tsx, src/components/ui/primitives/text-field/text-field.tsx, src/pages/deck-list-page/deck-list-page.tsx, src/pages/deck-page/deck-page.tsx
Clear Filters button feature added.
=> Clear filter

src/components/forms/dialog-forms/card-dialog-form/card-dialog-form.tsx, src/components/forms/dialog-forms/container-components/dialog-form-section.tsx, src/components/forms/dialog-forms/deck-dialog-form/deck-dialog-form.tsx
=> no image section if no cover in dialogs

src/components/forms/create-new-password-form/create-new-password-from.styles.ts, src/components/forms/dialog-forms/dialog-forms.styles.ts, src/components/forms/forgot-password-form/forgot-password-form.styles.ts, src/components/forms/personal-Info-form/personal-info-form.styles.ts, src/components/forms/self-rate-form/self-rate-form.styles.ts, src/components/forms/sign-in-form/sign-in-form.styles.ts, src/components/forms/sign-up-form/sign-up-form.styles.ts, src/components/ui/design-system/color-pallet/color-pallet.styles.ts, src/components/ui/design-system/iconography/iconography.styles.ts, src/components/ui/layout-components/actions/actions.styles.ts, src/components/ui/layout-components/check-email/check-email.styles.ts, src/components/ui/layout-components/deck-title/deck-title.styles.ts, src/components/ui/layout-components/dropdowns/dropdowns.styles.ts, src/components/ui/layout-components/learn-card/learn-card.styles.ts, src/components/ui/layout-components/personal-info/personal-info.styles.ts, src/components/ui/layout-components/table-filter-bar/table-filter-bar.styles.ts, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.tsx, src/components/ui/layout-components/user-profile/user-profile.styles.ts, src/components/ui/primitives/checkbox/checkbox.tsx, src/components/ui/primitives/grade/grade.tsx, src/components/ui/primitives/image/image.tsx, src/components/ui/primitives/pagination/pagination.tsx, src/components/ui/primitives/progress/progress.tsx, src/components/ui/primitives/radio/radio.tsx, src/components/ui/primitives/select/select.tsx, src/components/ui/primitives/slider/slider.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.tsx, src/components/ui/primitives/toast/toast.tsx, src/pages/card-page/card-page.styles.ts, src/pages/deck-page/deck-page.styles.ts
=> refactor clsx

src/components/ui/layout-components/table-filter-bar/table-filter-bar.tsx, src/components/ui/primitives/slider/slider.stories.tsx, src/components/ui/primitives/slider/slider.tsx, src/pages/deck-list-page/deck-list-page.tsx, src/services/decks/decks-api.ts
hi guys, I'm ready to introduce a new feature in slider component: onValueCommit
=> added onValueCommit into slider

package.json, pnpm-lock.yaml, src/app/App.tsx, src/app/router.tsx, src/components/forms/sign-in-form/sign-in-form.tsx, src/components/forms/sign-up-form/sign-up-form.tsx, src/components/ui/layout-components/cards-header/cards-header.stories.tsx, src/components/ui/layout-components/cards-header/cards-header.tsx, src/components/ui/primitives/text-field/text-field.tsx, src/main.tsx, src/pages/sign-in-page/sign-in-page.tsx, src/services/auth/auth-api.ts, src/services/auth/auth.types.ts, src/services/flashcards-api.ts, src/services/flashcards-base-query.ts, src/shared/hooks/index.ts, src/shared/hooks/use-auth-context.ts, src/shared/schemes/schemes.ts, src/shared/ui/layout/layout.tsx
Enjoy!
Correct request flow reached! 💪
=> feature: login & refresh token & routing update

src/components/ui/layout-components/tables/container-components/header-cell/header-cell.tsx, src/components/ui/layout-components/tables/container-components/position-cell/position-cell.tsx, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.module.scss, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.tsx, src/components/ui/layout-components/tables/deck-table/deck-table.module.scss, src/components/ui/layout-components/tables/deck-table/deck-table.tsx, src/components/ui/primitives/select/select.module.scss, src/components/ui/primitives/select/select.tsx, src/components/ui/primitives/table/table.module.scss, src/components/ui/primitives/table/table.tsx
‼️dependency from PRs:
- https://github.com/atpradical/flash-cards-team/pull/273#issue-2427472876
- https://github.com/atpradical/flash-cards-team/pull/272#issue-2425628647
Минимальный адаптив таблицы для десктопов.
Заданы ширина столбцам, чтобы не было прыжков во время сортировки (замечание Андрея после ревью).
=> Adaptive table desktop

src/components/ui/layout-components/personal-info/personal-info.stories.tsx, src/components/ui/layout-components/personal-info/personal-info.tsx, src/pages/profile-page/profile-page.tsx
‼️Dependency: [Feature: logout #280](https://github.com/atpradical/flash-cards-team/pull/280)
Profile page data
=> Profile data

src/components/ui/layout-components/actions/actions.module.scss, src/components/ui/layout-components/actions/actions.styles.ts, src/components/ui/layout-components/actions/actions.tsx, src/components/ui/layout-components/tables/container-components/position-cell/position-cell.tsx, src/components/ui/layout-components/tables/deck-list-table-mobile/deck-list-table-mobile.module.scss, src/components/ui/layout-components/tables/deck-list-table-mobile/deck-list-table-mobile.stories.tsx, src/components/ui/layout-components/tables/deck-list-table-mobile/deck-list-table-mobile.tsx, src/components/ui/layout-components/tables/deck-list-table-mobile/index.ts, src/components/ui/layout-components/tables/deck-list-table/deck-list-table.tsx, src/components/ui/layout-components/tables/deck-table-mobile/deck-table-mobile.stories.tsx, src/components/ui/layout-components/tables/deck-table-mobile/deck-table-mobile.tsx, src/components/ui/layout-components/tables/deck-table-mobile/index.ts, src/components/ui/layout-components/tables/deck-table/deck-table.tsx, src/components/ui/layout-components/tables/index.ts, src/components/ui/primitives/slider/slider.module.scss, src/components/ui/primitives/slider/slider.tsx, src/components/ui/primitives/tab-switcher/tab-switcher.module.scss, src/pages/deck-list-page/deck-list-page.tsx, src/pages/deck-page/deck-page.tsx, src/shared/enums/screen-size.enum.ts, src/shared/hooks/index.ts, src/shared/hooks/use-deck-list-table-data.ts, src/shared/hooks/use-deck-table-data.ts
=> Mobile tables

src/components/ui/layout-components/confirm-email/confirm-email.tsx, src/components/ui/layout-components/personal-info/personal-info.module.scss, src/components/ui/layout-components/personal-info/personal-info.stories.tsx, src/components/ui/layout-components/personal-info/personal-info.styles.ts, src/components/ui/layout-components/personal-info/personal-info.tsx, src/pages/confirm-email-page/confirm-email-page.tsx, src/pages/profile-page/profile-page.tsx, src/services/auth/auth-api.ts, src/services/auth/auth-templates.ts, src/services/auth/auth.types.ts, src/shared/hooks/use-profile.ts
‼️Dependency on
- https://github.com/atpradical/flash-cards-team/pull/285
- https://github.com/atpradical/flash-cards-team/pull/287
- https://github.com/atpradical/flash-cards-team/pull/289
Enjoy!
=> Reconfirm email

src/components/forms/forgot-password-form/forgot-password-form.tsx, src/pages/password-recovery-page/password-recovery-page.tsx, src/pages/sign-up-page/sign-up-page.tsx, src/services/auth/auth-api.ts, src/services/auth/auth-templates.ts, src/services/auth/auth.types.ts, src/shared/enums/path.ts
‼️Dependency on
- https://github.com/atpradical/flash-cards-team/pull/285
- https://github.com/atpradical/flash-cards-team/pull/287
- https://github.com/atpradical/flash-cards-team/pull/289
- https://github.com/atpradical/flash-cards-team/pull/291
Enjoy!
=> Password recovery email

package.json, pnpm-lock.yaml, src/app/App.tsx, src/components/ui/primitives/toast/toast.module.scss, src/components/ui/primitives/toast/toast.stories.tsx, src/components/ui/primitives/toast/toast.tsx, src/styles/_toast.scss, src/styles/index.scss
=> feature: toastify instead of radix toast
